artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_query: SELECT * FROM startup.business_growth_data;
  load_data: artifacts/data_ingestion/startup.csv

demo:
  thisIsDemo: Hi